
package ru.ifmo.se.soap;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://soap.se.ifmo.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ru.ifmo.se.soap.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPersons", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.SearchPersons")
    @ResponseWrapper(localName = "searchPersonsResponse", targetNamespace = "http://soap.se.ifmo.ru/", className = "ru.ifmo.se.soap.SearchPersonsResponse")
    public List<Person> searchPersons(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonListRequestDto arg0);

}
